"$schema" = 'https://starship.rs/config-schema.json'

# 238 is the gray background.
# 246 is the off-white foreground.

### PROMPT FORMAT ###

add_newline = true

format = """\
[╭─](fg:238 bold)\
[ \
    ($status  )\
    ($cmd_duration  )\
    ($jobs  )\
    (${custom.direnv}  )\
    ((${custom.kernel} )($sudo )$directory )[](fg:238)\
    [$fill](fg:238 bold)\
\
    ([](fg:238)( $git_branch)\
    ( $git_commit)\
    ( $git_state)\
    ($git_status)\
    (  $java)\
    (  $python)\
    (  $golang)\
    (  $rust) )\
](bg:238 fg:246)\
$line_break\
[╰─ ](fg:238 bold)\
"""

[fill]
symbol = "·"
# Fill module has no format key, so style must be explicitly set.
style = "fg:238 bold"

[status]
disabled = false
format = "[$symbol](fg:red bg:238)"
map_symbol = true
success_symbol = ""
# Default failure symbol unless one of the other symbols matches.
symbol = "✘ $status"
not_executable_symbol = "✘ $status"
not_found_symbol = "✘ $status"
# Default signal symbol unless one of the other symbols matches.
signal_symbol = ' $signal_name\($status\)'
sigint_symbol = ' $signal_name\($status\)'
# Ideally want this to look like powerlevel10k: '✘ 0|127' or '✘ 0|SIGINT(2)'.
# Currently support for pipe status is too minimal for this, so it is disabled.
#pipestatus = true
#pipestatus_format = "$pipestatus"

[sudo]
disabled = false
format = "[$symbol](fg:yellow bg:238)"
symbol = ""

[custom.direnv]
when = "test ! -z $DIRENV_DIR"
format = "[direnv](fg:yellow bg:238)"
description = "Whether direnv is enabled."

[custom.kernel]
format = "[$output](fg:246 bold bg:238)"
description = "The current kernel according to uname."
shell = [ "sh", "-c", "starship-get-kernel" ]
when = true

[directory]
format = "([$read_only](fg:red bg:238) )[$path](fg:31 bg:238)"
truncation_length = 5
truncate_to_repo = false
read_only = ""

### SHELL STATUS (left) ###

[jobs]
format = "$symbol $number"
symbol = "bg"
symbol_threshold = 1
number_threshold = 1

[cmd_duration]
format = "$duration"
min_time = 1_000

### GIT (right) ###

[git_branch]
format = "[$symbol $branch(⇄$remote_branch)](fg:green bg:238)"
symbol = ""
only_attached = true

[git_commit]
format = "[$hash](fg:yellow bg:238)"
only_detached = true

[git_state]
format = "[$state](fg:red bg:238)[($progress_current/$progress_total)](fg:246 bg:238)"

[git_status]
format = "[$all_status$ahead_behind](fg:yellow bg:238)"
up_to_date = ""
conflicted = " ≠"
modified = " ●"
deleted = " ⌀"
# TODO show counts for ahead/behind when not diverged.
diverged = " ↑$ahead_count ↓$behind_count"
ahead = " ↑"
behind = " ↓"
untracked = " ?"
stashed = " "
staged = " +"
renamed = " »"

### TOOLS (right) ###

[java]
format = "[$symbol](fg:246 bold bg:238) $version"
symbol = ""

[python]
format = "$symbol $version $virtualenv"
symbol = ""

[golang]
format = "[$symbol](fg:246 bold bg:238) $version"
symbol = ""

[rust]
format = "$symbol $version $toolchain"
symbol = ""

