#!/usr/bin/env sh

options() {
    local delimiter="$1"

    local paths="$HOME/.nix-profile/share/applications /usr/share/applications"

    # Gather all desktop files.
    for path in $paths; do
        if [ -d "$path" ]; then
            local files="$(find "$path" -name '*.desktop')\n$files"
        fi
    done

    # List names of all apps.
    for file in $(printf "$files"); do
        local name="$(cat "$file" | grep -m1 ^Name= | sed -e 's/^Name=//')"
        printf "${file}${delimiter}${name}\n"
    done
}

keybinding() {
    echo 'ctrl-a'
}

prompt() {
    echo 'Apps: '
}

run() {
    local query="$1"
    local selection="$2"

    dex "$selection"
}

"$@"
