#!/usr/bin/env bash

options() {
   local delimiter="$1"

    # Window id class title
    local win_infos="$(wmctrl -l -x | awk '{$2=""; $4=""; $3=substr($3,index($3,".")+1); print $0}')"
    local win_count="$(echo "$win_infos" | wc -l)"
    for line_num in $(seq 1 "$win_count"); do
        local id="$(echo "$win_infos" | awk -v idx="$line_num" 'FNR==idx {print $1}')"
        local class="$(echo "$win_infos" | awk -v idx="$line_num" 'FNR==idx {print $2}')"
        local title="$(echo "$win_infos" | awk -v idx="$line_num" '$1=""; $2=""; FNR==idx {print $0}')"

        # Gives 0 based index.
        local desktop_index="$(xdotool get_desktop_for_window "$id")"
        # Awk expects 1 based index.
        local desktop_name="$(bspc query --desktops --names | awk "FNR==$desktop_index+1")"
        printf "${id}${delimiter}$desktop_name: [$class] $title\n"
    done
}

keybinding() {
    echo 'ctrl-w'
}

prompt() {
    echo 'Windows: '
}

run() {
    local query="$1"
    local selection="$2"

    wmctrl -ia "$selection"
}

"$@"
