#!/usr/bin/env sh

options() {
    local delimiter="$1"

    # Depends on the name of the launcher matching the name of the last focused window.
    # If this is not the case, some combo of xtitle and window manager commands
    # to get the last focused window are needed.
    name="$(xdotool getactivewindow getwindowname)"

    printf "${name}${delimiter}$name"
}

keybinding() {
    echo 'ctrl-t'
}

prompt() {
    echo 'Rename window: '
}

run() {
    local query="$1"
    local selection="$2"

    # If selection was passed, it is the same name as the current window.
    # Don't need to do anything.
    if [ "$query" ]; then
        xdotool getactivewindow set_window --name "$query"
    fi
}

"$@"
