#!/usr/bin/env sh

options() {
    local delimiter="$1"

    paths="$HOME/Applications /Applications /System/Applications"

    # Gather all app files.
    for path in $paths; do
        if [ -d "$path" ]; then
            if [ "$files" ]; then
                files="$files"$'\n'
            fi
            files="${files}$(find "$path" -maxdepth 2 -name '*.app')"
        fi
    done

    # List names of all apps, which may contain spaces.
    while IFS='\n' read -r file; do
        name="$(basename --suffix='.app' "$file")"
        printf "${file}${delimiter}${name}\n"
    done <<< "$files"
}

keybinding() {
    echo 'ctrl-a'
}

prompt() {
    echo 'Apps: '
}

run() {
    local query="$1"
    local selection="$2"

    open -na "$selection"
}

"$@"
