#!/usr/bin/env bash


CACHE_DIR=~/.cache/fzf-launcher
OUT_FILE="$CACHE_DIR/fzf_wrapper_$$"
RC_FILE="$CACHE_DIR/fzf_wrapper_rc_$$"

mkdir -p "$CACHE_DIR"

window_title='Fzf Launcher'

# Sticky for yabai requires SIP disabled.
yabai -m rule --add label=fzf app=alacritty title="$window_title" sticky=on manage=off border=off grid='4:4:1:1:2:2'

alacritty \
    --option 'window.dimensions.lines: 20' \
    --option 'window.dimensions.columns: 100' \
    --option 'window.decorations: none' \
    --option "window.title: $window_title" \
    --command sh -c "fzf --layout=reverse --border=rounded "$@" > "$OUT_FILE"; echo \$? > "$RC_FILE""

yabai -m rule --remove fzf

cat "$OUT_FILE"
rc="$(cat "$RC_FILE")"

rm -f "$OUT_FILE"
rm -f "$RC_FILE"

exit "$rc"
