#!/usr/bin/env sh

CACHE_DIR=~/.cache/fzf-launcher
OUT_FILE="$CACHE_DIR/fzf_wrapper_$$"
RC_FILE="$CACHE_DIR/fzf_wrapper_rc_$$"

mkdir -p "$CACHE_DIR"

window_title='Fzf Launcher'

# Sticky for yabai requires SIP disabled.
yabai -m rule --add label=fzf app=kitty title="$window_title" sticky=on manage=off border=off grid='4:4:1:1:2:2'

kitty \
    --override remember_window_size=no \
    --override initial_window_width=100c \
    --override initial_window_height=20c \
    --override hide_window_decorations=yes \
    --override background_image=none \
    --title "$window_title" \
    sh -c "fzf --layout=reverse --margin='1,1' "$@" > "$OUT_FILE"; echo \$? > "$RC_FILE""

yabai -m rule --remove fzf

cat "$OUT_FILE"
rc="$(cat "$RC_FILE")"

rm -f "$OUT_FILE"
rm -f "$RC_FILE"

exit "$rc"
