#!/usr/bin/env bash

options() {
    local delimiter="$1"

    local options='skhd\nyabai'
    # Options to select and pass back in to this script are the same.
    paste --delimiters="$delimiter" <(printf "$options") <(printf "$options")
}

keybinding() {
    echo 'ctrl-r'
}

prompt() {
    echo 'Reload: '
}

run() {
    local query="$1"
    local selection="$2"

    declare -A action_to_cmd
    action_to_cmd['skhd']='launchctl stop skhd && launchctl start skhd'
    action_to_cmd['yabai']='launchctl stop yabai && launchctl start yabai'

    eval "${action_to_cmd[$selection]}"
}

"$@"
