#!/usr/bin/env sh

options() {
    local delimiter="$1"

    local name="$(yabai -m query --spaces --space | jq -r '.label')"
    if [ "$name" ]; then
        printf "${name}${delimiter}${name}"
    fi
}

keybinding() {
    echo 'ctrl-s'
}

prompt() {
    echo 'Rename: '
}

run() {
    local query="$1"
    local selection="$2"

    # If selection was passed, it is the same name as the current desktop,
    # don't need to do anything.
    yabai -m space --label "$query"
}

"$@"
