#!/usr/bin/env bash

options() {
    local delimiter="$1"

    # TODO: Mark minimized windows.

    # Get window id app title
    local win_info_json="$(yabai -m query --windows)"

    local ids="$(echo "$win_info_json" | jq -r '.[].id')"
    local space_indices="$(echo "$win_info_json" | jq -r '.[].space')"
    local apps="$(echo "$win_info_json" | jq -r '.[].app')"
    local titles="$(echo "$win_info_json" | jq -r '.[].title')"

    # Label for each space is on line corresponding to its space index.
    local space_labels="$(yabai -m query --spaces | jq -r '.[].label')"

    local num_lines="$(echo "$ids" | wc -l)"

    for line_num in $(seq 1 "$num_lines"); do
        local win_id="$(echo "$ids" | awk -v idx="$line_num" 'FNR==idx')"
        local space_index="$(echo "$space_indices" | awk -v idx="$line_num" 'FNR==idx')"
        local app="$(echo "$apps" | awk -v idx="$line_num" 'FNR==idx')"
        local title="$(echo "$titles" | awk -v idx="$line_num" 'FNR==idx')"

        # Check if this window's space has a label.
        local space_label="$(echo "$space_labels" | awk -v idx="$space_index" 'FNR==idx')"
        if [ "$space_label" ]; then
            local space="$space_label"
        else
            local space="$space_index"
        fi

        printf "${win_id}${delimiter}${space}: [$app] $title\n"
    done
}

keybinding() {
    echo 'ctrl-w'
}

prompt() {
    echo 'Window: '
}

run() {
    local query="$1"
    local selection="$2"

    yabai -m window --focus "$selection"
}

"$@"
