#!/usr/bin/env sh

spacebar -m config position top
spacebar -m config height 22

spacebar -m config title off
spacebar -m config spaces on
spacebar -m config clock off
spacebar -m config power off

spacebar -m config spacing_left 10
spacebar -m config spacing_right 10

#spacebar -m config text_font "Source Code Pro:Bold:16"
spacebar -m config icon_font "MesloLGS NF:Regular:16"
spacebar -m config text_font "$(spacebar -m config icon_font)"

spacebar -m config background_color 0xff19233c
spacebar -m config foreground_color 0xffffffff

spacebar -m config space_icon_color 0xffeb7a34
spacebar -m config power_icon_color "$(spacebar -m config foreground_color)"
spacebar -m config battery_icon_color "$(spacebar -m config foreground_color)"
spacebar -m config dnd_icon_color "$(spacebar -m config foreground_color)"
spacebar -m config clock_icon_color "$(spacebar -m config foreground_color)"

spacebar -m config clock_format "%A %I:%M %p"
spacebar -m config power_icon_strip  

spacebar -m config clock_icon ' '
# TODO: Verify cpu amd mem %.
#spacebar-cpu-mem &

# Load yabai space information
spacebar-yabai-spaces

#spacebar -m config right_shell_command 'spacebar-right-shell'
#spacebar -m config right_shell_icon ' '
#spacebar -m config right_shell off

### SPACEBAR SETTINGS FOR YABAI ###

# Add padding to the top or bottom of all spaces regardless of the display they belong to.
bar_height="$(spacebar -m config height)"
yabai -m config external_bar all:"$bar_height":0

# Window crewate and destroy events do not seem to fire, so use application launched and deactivated events instead.
spacebar_events='space_changed mission_control_exit window_focused window_minimized window_deminimized application_launched application_deactivated'
for event in $spacebar_events; do
    yabai -m signal --add event="$event" action='spacebar-yabai-spaces' label=spacebar-spaces-"$event"
done

yabai -m signal --add event='mission_control_enter' action='spacebar -m config position bottom'
yabai -m signal --add event='mission_control_exit' action='spacebar -m config position top'

echo "spacebar configuration loaded."

