#!/usr/bin/env sh

### CONFIG VARIABLES ###
normal_border_width=1
marked_border_width=5
border_on_color="#a6a6a6"
#border_off_color="#817f7f"
border_off_color="#000000"

### FUNCTIONS ###

# Pass all files in sxhkd config directory as extra configs
sxhkd ~/.config/sxhkd/* &

bspc config border_width "$normal_border_width"

bspc config focused_border_color "$border_on_color"
bspc config active_border_color "$border_off_color"
bspc config normal_border_color "$border_off_color"

bspc config window_gap 5

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

### SUBSCRIBE TO EVENTS ###

bspc subscribe node_add | while read event monitor_id desktop_id ip_id node_id; do
    bspwm-set-desktop-status "$desktop_id"
done &

bspc subscribe node_remove | while read event monitor_id desktop_id node_id; do
    bspwm-set-desktop-status "$desktop_id"
done &

bspc subscribe node_swap | while read event monitor_id desktop_id node_id; do
    bspwm-set-desktop-status "$desktop_id"
done &

bspc subscribe node_focus | while read event monitor_id desktop_id node_id; do
    bspwm-set-desktop-status "$desktop_id"
done &

bspc subscribe node_transfer | while read event src_monitor_id src_desktop_id src_node_id dst_monitor_id dst_desktop_id dst_node_id; do
    bspwm-set-desktop-status "$src_desktop_id"
    bspwm-set-desktop-status "$dst_desktop_id"
done &

bspc subscribe desktop_layout | while read event monitor_id desktop_id layout; do
    bspwm-set-desktop-status "$desktop_id"
done &

# TODO: Fix this to show marked nodes.
#   It seems that even when specifying a specific node, the config changes apply to all nodes.
bspc subscribe node_flag | while read event monitor_id desktop_id node_id flag value; do
    if [ "$flag" = marked ]; then
#        if [ "$value" = on ]; then
#             bspc config -n "$node_id" border_width "$marked_border_width"

#             bspc config -n "$node_id" focused_border_color "$border_on_color"
#             bspc config -n "$node_id" active_border_color "$border_on_color"
#             bspc config -n "$node_id" normal_border_color "$border_on_color"
#         else
#             bspc config -n "$node_id" border_width "$normal_border_width"

#             bspc config -n "$node_id" focused_border_color "$border_on_color"
#             bspc config -n "$node_id" active_border_color "$border_off_color"
#             bspc config -n "$node_id" normal_border_color "$border_off_color"
#         fi

        bspwm-set-desktop-status "$desktop_id"
    fi
done &
