#!/usr/bin/env sh

### CONFIG VARIABLES ###

normal_border_width=3
border_on_color="#FFFFFF"
border_off_color="#FFFFFF"
preselect_color="#FF0000"

# Initial desktops to create.
bspc monitor --reset-desktops Files Web

bspc config border_width "$normal_border_width"
bspc config focused_border_color "$border_on_color"
bspc config active_border_color "$border_off_color"
bspc config normal_border_color "$border_off_color"
# Turn off borders by default. Applications that want them can add a rule to turn them on with the above appearance.
# However, if bspwm is reloaded with existing windows, they get borders applied for some reason.
bspc rule --add '*' border=off

bspc config presel_feedback_color "$preselect_color"

bspc config window_gap 5
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config single_monocle true

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspwm-listener-daemon

