#!/usr/bin/env sh

### CONFIG VARIABLES ###

normal_border_width=1
border_on_color="#a6a6a6"
border_off_color="#000000"
preselect_color="#FF0000"

# Initial desktops to create.
bspc monitor --reset-desktops Files Web

bspc config border_width "$normal_border_width"

bspc config focused_border_color "$border_on_color"
bspc config active_border_color "$border_off_color"
bspc config normal_border_color "$border_off_color"

bspc config presel_feedback_color "$preselect_color"

bspc config window_gap 5
bspc config gapless_monocle true

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Start daemons that must run after window manager.
"$STARTUP_DIR"/bspwm/load.sh &

