#!/usr/bin/env sh

### MOUSE SETTINGS ###

yabai -m config mouse_modifier               alt
# Left click.
yabai -m config mouse_action1                move
# Right click.
yabai -m config mouse_action2                resize
# Disabled while mouse modifier is held.
yabai -m config focus_follows_mouse          autofocus
yabai -m config mouse_follows_focus          on

# Add new windows to right and bottom.
yabai -m config window_placement             second_child

### WINDOW EFFECTS ###

yabai -m config window_shadow                off
yabai -m config window_opacity               off

### GAPS AND PADDING ###

# Space between window and each edge of screen.
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
# Space between windows.
yabai -m config window_gap                   5

### MISC SETTINGS ###

yabai -m config auto_balance                 off
yabai -m config layout                       stack

# Load startup scripts.
startup_script="$STARTUP_DIR"/yabai/load.sh
[ -x "$startup_script" ] && "$startup_script"

echo "yabai configuration loaded."

